package com.sgs.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 13 10:42:07 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SgsCustomersVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SgsCustomersVOImpl() {
    }
}

