package com.sgs.model.entity;

import com.sgs.model.service.SGSAppModuleImpl;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 14 16:21:57 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SgsArInvoiceLinesImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ArInvoiceLinesId,
        BuId,
        AccRecInvoicesId,
        ArInvoiceNo,
        ArInvoiceLinesNo,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy,
        TOTALAMOUNT,
        AMOUNTPAID,
        REMAININGPAYMENTS;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    private static final ADFLogger LOG = ADFLogger.createADFLogger(SgsArInvoiceLinesImpl.class);


    public static final int ARINVOICELINESID = AttributesEnum.ArInvoiceLinesId.index();
    public static final int BUID = AttributesEnum.BuId.index();
    public static final int ACCRECINVOICESID = AttributesEnum.AccRecInvoicesId.index();
    public static final int ARINVOICENO = AttributesEnum.ArInvoiceNo.index();
    public static final int ARINVOICELINESNO = AttributesEnum.ArInvoiceLinesNo.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int TOTALAMOUNT = AttributesEnum.TOTALAMOUNT.index();
    public static final int AMOUNTPAID = AttributesEnum.AMOUNTPAID.index();
    public static final int REMAININGPAYMENTS = AttributesEnum.REMAININGPAYMENTS.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SgsArInvoiceLinesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.sgs.model.entity.SgsArInvoiceLines");
    }


    /**
     * Gets the attribute value for ArInvoiceLinesId, using the alias name ArInvoiceLinesId.
     * @return the value of ArInvoiceLinesId
     */
    public Integer getArInvoiceLinesId() {
        return (Integer) getAttributeInternal(ARINVOICELINESID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ArInvoiceLinesId.
     * @param value value to set the ArInvoiceLinesId
     */
    public void setArInvoiceLinesId(Integer value) {
        setAttributeInternal(ARINVOICELINESID, value);
    }

    /**
     * Gets the attribute value for BuId, using the alias name BuId.
     * @return the value of BuId
     */
    public Integer getBuId() {
        return (Integer) getAttributeInternal(BUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuId.
     * @param value value to set the BuId
     */
    public void setBuId(Integer value) {
        setAttributeInternal(BUID, value);
    }

    /**
     * Gets the attribute value for AccRecInvoicesId, using the alias name AccRecInvoicesId.
     * @return the value of AccRecInvoicesId
     */
    public Integer getAccRecInvoicesId() {
        return (Integer) getAttributeInternal(ACCRECINVOICESID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AccRecInvoicesId.
     * @param value value to set the AccRecInvoicesId
     */
    public void setAccRecInvoicesId(Integer value) {
        setAttributeInternal(ACCRECINVOICESID, value);
    }

    /**
     * Gets the attribute value for ArInvoiceNo, using the alias name ArInvoiceNo.
     * @return the value of ArInvoiceNo
     */
    public String getArInvoiceNo() {
        return (String) getAttributeInternal(ARINVOICENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ArInvoiceNo.
     * @param value value to set the ArInvoiceNo
     */
    public void setArInvoiceNo(String value) {
        setAttributeInternal(ARINVOICENO, value);
    }

    /**
     * Gets the attribute value for ArInvoiceLinesNo, using the alias name ArInvoiceLinesNo.
     * @return the value of ArInvoiceLinesNo
     */
    public String getArInvoiceLinesNo() {
        return (String) getAttributeInternal(ARINVOICELINESNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ArInvoiceLinesNo.
     * @param value value to set the ArInvoiceLinesNo
     */
    public void setArInvoiceLinesNo(String value) {
        setAttributeInternal(ARINVOICELINESNO, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Date getUpdatedDate() {
        return (Date) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedDate.
     * @param value value to set the UpdatedDate
     */
    public void setUpdatedDate(Date value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }


    /**
     * Gets the attribute value for TOTALAMOUNT, using the alias name TOTALAMOUNT.
     * @return the value of TOTALAMOUNT
     */
    public BigDecimal getTOTALAMOUNT() {
        return (BigDecimal) getAttributeInternal(TOTALAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TOTALAMOUNT.
     * @param value value to set the TOTALAMOUNT
     */
    public void setTOTALAMOUNT(BigDecimal value) {
        setAttributeInternal(TOTALAMOUNT, value);
    }

    /**
     * Gets the attribute value for AMOUNTPAID, using the alias name AMOUNTPAID.
     * @return the value of AMOUNTPAID
     */
    public BigDecimal getAMOUNTPAID() {
        return (BigDecimal) getAttributeInternal(AMOUNTPAID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AMOUNTPAID.
     * @param value value to set the AMOUNTPAID
     */
    public void setAMOUNTPAID(BigDecimal value) {
        setAttributeInternal(AMOUNTPAID, value);
    }

    /**
     * Gets the attribute value for REMAININGPAYMENTS, using the alias name REMAININGPAYMENTS.
     * @return the value of REMAININGPAYMENTS
     */
    public BigDecimal getREMAININGPAYMENTS() {
        return (BigDecimal) getAttributeInternal(REMAININGPAYMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for REMAININGPAYMENTS.
     * @param value value to set the REMAININGPAYMENTS
     */
    public void setREMAININGPAYMENTS(BigDecimal value) {
        setAttributeInternal(REMAININGPAYMENTS, value);
    }

    /**
     * @param arInvoiceLinesId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer arInvoiceLinesId) {
        return new Key(new Object[] { arInvoiceLinesId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        try {
            SGSAppModuleImpl am = new SGSAppModuleImpl();
            setArInvoiceLinesId(am.getDBSequence("SGS_AR_INVOICE_LINES_SEQ"));
        } catch (Exception e) {
            LOG.severe(e);
        }
    }
}

