package com.sgs.model.entity;

import com.sgs.model.service.SGSAppModuleImpl;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 14 16:19:11 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SgsApInvoiceLinesImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ApInvoiceLinesId,
        BuId,
        AccPayInvoicesId,
        ApInvoiceNo,
        ApInvoiceLinesNo,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy,
        TOTALAMOUNT,
        AMOUNTPAID,
        REMAININGPAYMENTS;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    private static final ADFLogger LOG = ADFLogger.createADFLogger(SgsApInvoiceLinesImpl.class);


    public static final int APINVOICELINESID = AttributesEnum.ApInvoiceLinesId.index();
    public static final int BUID = AttributesEnum.BuId.index();
    public static final int ACCPAYINVOICESID = AttributesEnum.AccPayInvoicesId.index();
    public static final int APINVOICENO = AttributesEnum.ApInvoiceNo.index();
    public static final int APINVOICELINESNO = AttributesEnum.ApInvoiceLinesNo.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int TOTALAMOUNT = AttributesEnum.TOTALAMOUNT.index();
    public static final int AMOUNTPAID = AttributesEnum.AMOUNTPAID.index();
    public static final int REMAININGPAYMENTS = AttributesEnum.REMAININGPAYMENTS.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SgsApInvoiceLinesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.sgs.model.entity.SgsApInvoiceLines");
    }


    /**
     * Gets the attribute value for ApInvoiceLinesId, using the alias name ApInvoiceLinesId.
     * @return the value of ApInvoiceLinesId
     */
    public Integer getApInvoiceLinesId() {
        return (Integer) getAttributeInternal(APINVOICELINESID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApInvoiceLinesId.
     * @param value value to set the ApInvoiceLinesId
     */
    public void setApInvoiceLinesId(Integer value) {
        setAttributeInternal(APINVOICELINESID, value);
    }

    /**
     * Gets the attribute value for BuId, using the alias name BuId.
     * @return the value of BuId
     */
    public Integer getBuId() {
        return (Integer) getAttributeInternal(BUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuId.
     * @param value value to set the BuId
     */
    public void setBuId(Integer value) {
        setAttributeInternal(BUID, value);
    }

    /**
     * Gets the attribute value for AccPayInvoicesId, using the alias name AccPayInvoicesId.
     * @return the value of AccPayInvoicesId
     */
    public Integer getAccPayInvoicesId() {
        return (Integer) getAttributeInternal(ACCPAYINVOICESID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AccPayInvoicesId.
     * @param value value to set the AccPayInvoicesId
     */
    public void setAccPayInvoicesId(Integer value) {
        setAttributeInternal(ACCPAYINVOICESID, value);
    }

    /**
     * Gets the attribute value for ApInvoiceNo, using the alias name ApInvoiceNo.
     * @return the value of ApInvoiceNo
     */
    public String getApInvoiceNo() {
        return (String) getAttributeInternal(APINVOICENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApInvoiceNo.
     * @param value value to set the ApInvoiceNo
     */
    public void setApInvoiceNo(String value) {
        setAttributeInternal(APINVOICENO, value);
    }

    /**
     * Gets the attribute value for ApInvoiceLinesNo, using the alias name ApInvoiceLinesNo.
     * @return the value of ApInvoiceLinesNo
     */
    public String getApInvoiceLinesNo() {
        return (String) getAttributeInternal(APINVOICELINESNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApInvoiceLinesNo.
     * @param value value to set the ApInvoiceLinesNo
     */
    public void setApInvoiceLinesNo(String value) {
        setAttributeInternal(APINVOICELINESNO, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Date getUpdatedDate() {
        return (Date) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedDate.
     * @param value value to set the UpdatedDate
     */
    public void setUpdatedDate(Date value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }


    /**
     * Gets the attribute value for TOTALAMOUNT, using the alias name TOTALAMOUNT.
     * @return the value of TOTALAMOUNT
     */
    public BigDecimal getTOTALAMOUNT() {
        return (BigDecimal) getAttributeInternal(TOTALAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TOTALAMOUNT.
     * @param value value to set the TOTALAMOUNT
     */
    public void setTOTALAMOUNT(BigDecimal value) {
        setAttributeInternal(TOTALAMOUNT, value);
    }

    /**
     * Gets the attribute value for AMOUNTPAID, using the alias name AMOUNTPAID.
     * @return the value of AMOUNTPAID
     */
    public BigDecimal getAMOUNTPAID() {
        return (BigDecimal) getAttributeInternal(AMOUNTPAID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AMOUNTPAID.
     * @param value value to set the AMOUNTPAID
     */
    public void setAMOUNTPAID(BigDecimal value) {
        setAttributeInternal(AMOUNTPAID, value);
    }

    /**
     * Gets the attribute value for REMAININGPAYMENTS, using the alias name REMAININGPAYMENTS.
     * @return the value of REMAININGPAYMENTS
     */
    public BigDecimal getREMAININGPAYMENTS() {
        return (BigDecimal) getAttributeInternal(REMAININGPAYMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for REMAININGPAYMENTS.
     * @param value value to set the REMAININGPAYMENTS
     */
    public void setREMAININGPAYMENTS(BigDecimal value) {
        setAttributeInternal(REMAININGPAYMENTS, value);
    }

    /**
     * @param apInvoiceLinesId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer apInvoiceLinesId) {
        return new Key(new Object[] { apInvoiceLinesId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        try {
            SGSAppModuleImpl am = new SGSAppModuleImpl();
            setApInvoiceLinesId(am.getDBSequence("SGS_AP_INVOICE_LINES_SEQ"));
        } catch (Exception e) {
            LOG.severe(e);
        }
    }
}

