package com.sgs.model.entity;

import com.sgs.model.service.SGSAppModuleImpl;

import java.sql.Date;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 07 09:21:26 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SgsAllocationRuleSetupImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ArsId,
        AllocationRuleId,
        CostIdentificationId,
        AllocationBasis,
        OffsetAccount,
        TargetAccount,
        EffectiveStartDate,
        EffectiveEndDate,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ARSID = AttributesEnum.ArsId.index();
    public static final int ALLOCATIONRULEID = AttributesEnum.AllocationRuleId.index();
    public static final int COSTIDENTIFICATIONID = AttributesEnum.CostIdentificationId.index();
    public static final int ALLOCATIONBASIS = AttributesEnum.AllocationBasis.index();
    public static final int OFFSETACCOUNT = AttributesEnum.OffsetAccount.index();
    public static final int TARGETACCOUNT = AttributesEnum.TargetAccount.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int EFFECTIVEENDDATE = AttributesEnum.EffectiveEndDate.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    private static final ADFLogger LOG = ADFLogger.createADFLogger(SgsAllocationRuleSetupImpl.class);

    /**
     * This is the default constructor (do not remove).
     */
    public SgsAllocationRuleSetupImpl() {
    }

    /**
     * Gets the attribute value for ArsId, using the alias name ArsId.
     * @return the value of ArsId
     */
    public Integer getArsId() {
        return (Integer) getAttributeInternal(ARSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ArsId.
     * @param value value to set the ArsId
     */
    public void setArsId(Integer value) {
        setAttributeInternal(ARSID, value);
    }

    /**
     * Gets the attribute value for AllocationRuleId, using the alias name AllocationRuleId.
     * @return the value of AllocationRuleId
     */
    public String getAllocationRuleId() {
        return (String) getAttributeInternal(ALLOCATIONRULEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllocationRuleId.
     * @param value value to set the AllocationRuleId
     */
    public void setAllocationRuleId(String value) {
        setAttributeInternal(ALLOCATIONRULEID, value);
    }

    /**
     * Gets the attribute value for CostIdentificationId, using the alias name CostIdentificationId.
     * @return the value of CostIdentificationId
     */
    public String getCostIdentificationId() {
        return (String) getAttributeInternal(COSTIDENTIFICATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CostIdentificationId.
     * @param value value to set the CostIdentificationId
     */
    public void setCostIdentificationId(String value) {
        setAttributeInternal(COSTIDENTIFICATIONID, value);
    }

    /**
     * Gets the attribute value for AllocationBasis, using the alias name AllocationBasis.
     * @return the value of AllocationBasis
     */
    public String getAllocationBasis() {
        return (String) getAttributeInternal(ALLOCATIONBASIS);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllocationBasis.
     * @param value value to set the AllocationBasis
     */
    public void setAllocationBasis(String value) {
        setAttributeInternal(ALLOCATIONBASIS, value);
    }

    /**
     * Gets the attribute value for OffsetAccount, using the alias name OffsetAccount.
     * @return the value of OffsetAccount
     */
    public String getOffsetAccount() {
        return (String) getAttributeInternal(OFFSETACCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for OffsetAccount.
     * @param value value to set the OffsetAccount
     */
    public void setOffsetAccount(String value) {
        setAttributeInternal(OFFSETACCOUNT, value);
    }

    /**
     * Gets the attribute value for TargetAccount, using the alias name TargetAccount.
     * @return the value of TargetAccount
     */
    public String getTargetAccount() {
        return (String) getAttributeInternal(TARGETACCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TargetAccount.
     * @param value value to set the TargetAccount
     */
    public void setTargetAccount(String value) {
        setAttributeInternal(TARGETACCOUNT, value);
    }

    /**
     * Gets the attribute value for EffectiveStartDate, using the alias name EffectiveStartDate.
     * @return the value of EffectiveStartDate
     */
    public Date getEffectiveStartDate() {
        return (Date) getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveStartDate.
     * @param value value to set the EffectiveStartDate
     */
    public void setEffectiveStartDate(Date value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**
     * Gets the attribute value for EffectiveEndDate, using the alias name EffectiveEndDate.
     * @return the value of EffectiveEndDate
     */
    public Date getEffectiveEndDate() {
        return (Date) getAttributeInternal(EFFECTIVEENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveEndDate.
     * @param value value to set the EffectiveEndDate
     */
    public void setEffectiveEndDate(Date value) {
        setAttributeInternal(EFFECTIVEENDDATE, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Date getUpdatedDate() {
        return (Date) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedDate.
     * @param value value to set the UpdatedDate
     */
    public void setUpdatedDate(Date value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * @param arsId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer arsId) {
        return new Key(new Object[] { arsId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.sgs.model.entity.SgsAllocationRuleSetup");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        try {
            SGSAppModuleImpl am = new SGSAppModuleImpl();
            setArsId(am.getDBSequence("SGS_ALLOCATION_RULE_SETUP_SEQ"));
        } catch (Exception e) {
            LOG.severe(e);
        }
    }
}

