package com.sgs.model.entity;

import com.sgs.model.service.SGSAppModuleImpl;

import java.sql.Date;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 12 19:35:19 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
@SuppressWarnings("oracle.jdeveloper.java.semantic-warning")
public class SgsBillTypeImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        BillTypeId,
        BillName,
        BillTypeName,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int BILLTYPEID = AttributesEnum.BillTypeId.index();
    public static final int BILLNAME = AttributesEnum.BillName.index();
    public static final int BILLTYPENAME = AttributesEnum.BillTypeName.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    private static final ADFLogger LOG = ADFLogger.createADFLogger(SgsBillTypeImpl.class);

    /**
     * This is the default constructor (do not remove).
     */
    public SgsBillTypeImpl() {
    }

    /**
     * Gets the attribute value for BillTypeId, using the alias name BillTypeId.
     * @return the value of BillTypeId
     */
    public Integer getBillTypeId() {
        return (Integer) getAttributeInternal(BILLTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillTypeId.
     * @param value value to set the BillTypeId
     */
    public void setBillTypeId(Integer value) {
        setAttributeInternal(BILLTYPEID, value);
    }

    /**
     * Gets the attribute value for BillName, using the alias name BillName.
     * @return the value of BillName
     */
    public String getBillName() {
        return (String) getAttributeInternal(BILLNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillName.
     * @param value value to set the BillName
     */
    public void setBillName(String value) {
        setAttributeInternal(BILLNAME, value);
    }

    /**
     * Gets the attribute value for BillTypeName, using the alias name BillTypeName.
     * @return the value of BillTypeName
     */
    public String getBillTypeName() {
        return (String) getAttributeInternal(BILLTYPENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillTypeName.
     * @param value value to set the BillTypeName
     */
    public void setBillTypeName(String value) {
        setAttributeInternal(BILLTYPENAME, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Date getUpdatedDate() {
        return (Date) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedDate.
     * @param value value to set the UpdatedDate
     */
    public void setUpdatedDate(Date value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * @param billTypeId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer billTypeId) {
        return new Key(new Object[] { billTypeId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.sgs.model.entity.SgsBillType");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        try {
            SGSAppModuleImpl am = new SGSAppModuleImpl();
            setBillTypeId(am.getDBSequence("SGS_BILL_TYPE_SEQ"));
        } catch (Exception e) {
            LOG.severe(e);
        }
    }
}

