package com.sgs.model.entity;

import com.sgs.model.service.SGSAppModuleImpl;

import java.sql.Date;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 12 19:35:36 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SgsContractHeaderImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ContractHeaderId,
        BuId,
        ConNo,
        CustomersId,
        BillTypeId,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CONTRACTHEADERID = AttributesEnum.ContractHeaderId.index();
    public static final int BUID = AttributesEnum.BuId.index();
    public static final int CONNO = AttributesEnum.ConNo.index();
    public static final int CUSTOMERSID = AttributesEnum.CustomersId.index();
    public static final int BILLTYPEID = AttributesEnum.BillTypeId.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    private static final ADFLogger LOG = ADFLogger.createADFLogger(SgsContractHeaderImpl.class);

    /**
     * This is the default constructor (do not remove).
     */
    public SgsContractHeaderImpl() {
    }

    /**
     * Gets the attribute value for ContractHeaderId, using the alias name ContractHeaderId.
     * @return the value of ContractHeaderId
     */
    public Integer getContractHeaderId() {
        return (Integer) getAttributeInternal(CONTRACTHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractHeaderId.
     * @param value value to set the ContractHeaderId
     */
    public void setContractHeaderId(Integer value) {
        setAttributeInternal(CONTRACTHEADERID, value);
    }

    /**
     * Gets the attribute value for BuId, using the alias name BuId.
     * @return the value of BuId
     */
    public Integer getBuId() {
        return (Integer) getAttributeInternal(BUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuId.
     * @param value value to set the BuId
     */
    public void setBuId(Integer value) {
        setAttributeInternal(BUID, value);
    }

    /**
     * Gets the attribute value for ConNo, using the alias name ConNo.
     * @return the value of ConNo
     */
    public String getConNo() {
        return (String) getAttributeInternal(CONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConNo.
     * @param value value to set the ConNo
     */
    public void setConNo(String value) {
        setAttributeInternal(CONNO, value);
    }

    /**
     * Gets the attribute value for CustomersId, using the alias name CustomersId.
     * @return the value of CustomersId
     */
    public Integer getCustomersId() {
        return (Integer) getAttributeInternal(CUSTOMERSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomersId.
     * @param value value to set the CustomersId
     */
    public void setCustomersId(Integer value) {
        setAttributeInternal(CUSTOMERSID, value);
    }

    /**
     * Gets the attribute value for BillTypeId, using the alias name BillTypeId.
     * @return the value of BillTypeId
     */
    public Integer getBillTypeId() {
        return (Integer) getAttributeInternal(BILLTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillTypeId.
     * @param value value to set the BillTypeId
     */
    public void setBillTypeId(Integer value) {
        setAttributeInternal(BILLTYPEID, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Date getUpdatedDate() {
        return (Date) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedDate.
     * @param value value to set the UpdatedDate
     */
    public void setUpdatedDate(Date value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * @param contractHeaderId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer contractHeaderId) {
        return new Key(new Object[] { contractHeaderId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.sgs.model.entity.SgsContractHeader");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        try {
            SGSAppModuleImpl am = new SGSAppModuleImpl();
            setContractHeaderId(am.getDBSequence("SGS_CONTRACT_HEADER_SEQ"));
        } catch (Exception e) {
            LOG.severe(e);
        }
    }
}

