package com.sgs.model.entity;

import com.sgs.model.service.SGSAppModuleImpl;

import java.sql.Date;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 12 19:35:54 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SgsCustomersImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CustomersId,
        BuId,
        CustCode,
        CustName,
        CustConN0,
        CustAddress,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CUSTOMERSID = AttributesEnum.CustomersId.index();
    public static final int BUID = AttributesEnum.BuId.index();
    public static final int CUSTCODE = AttributesEnum.CustCode.index();
    public static final int CUSTNAME = AttributesEnum.CustName.index();
    public static final int CUSTCONN0 = AttributesEnum.CustConN0.index();
    public static final int CUSTADDRESS = AttributesEnum.CustAddress.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    private static final ADFLogger LOG = ADFLogger.createADFLogger(SgsCustomersImpl.class);

    /**
     * This is the default constructor (do not remove).
     */
    public SgsCustomersImpl() {
    }

    /**
     * Gets the attribute value for CustomersId, using the alias name CustomersId.
     * @return the value of CustomersId
     */
    public Integer getCustomersId() {
        return (Integer) getAttributeInternal(CUSTOMERSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomersId.
     * @param value value to set the CustomersId
     */
    public void setCustomersId(Integer value) {
        setAttributeInternal(CUSTOMERSID, value);
    }

    /**
     * Gets the attribute value for BuId, using the alias name BuId.
     * @return the value of BuId
     */
    public Integer getBuId() {
        return (Integer) getAttributeInternal(BUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuId.
     * @param value value to set the BuId
     */
    public void setBuId(Integer value) {
        setAttributeInternal(BUID, value);
    }

    /**
     * Gets the attribute value for CustCode, using the alias name CustCode.
     * @return the value of CustCode
     */
    public String getCustCode() {
        return (String) getAttributeInternal(CUSTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustCode.
     * @param value value to set the CustCode
     */
    public void setCustCode(String value) {
        setAttributeInternal(CUSTCODE, value);
    }

    /**
     * Gets the attribute value for CustName, using the alias name CustName.
     * @return the value of CustName
     */
    public String getCustName() {
        return (String) getAttributeInternal(CUSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustName.
     * @param value value to set the CustName
     */
    public void setCustName(String value) {
        setAttributeInternal(CUSTNAME, value);
    }

    /**
     * Gets the attribute value for CustConN0, using the alias name CustConN0.
     * @return the value of CustConN0
     */
    public String getCustConN0() {
        return (String) getAttributeInternal(CUSTCONN0);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustConN0.
     * @param value value to set the CustConN0
     */
    public void setCustConN0(String value) {
        setAttributeInternal(CUSTCONN0, value);
    }

    /**
     * Gets the attribute value for CustAddress, using the alias name CustAddress.
     * @return the value of CustAddress
     */
    public String getCustAddress() {
        return (String) getAttributeInternal(CUSTADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustAddress.
     * @param value value to set the CustAddress
     */
    public void setCustAddress(String value) {
        setAttributeInternal(CUSTADDRESS, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Date getUpdatedDate() {
        return (Date) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedDate.
     * @param value value to set the UpdatedDate
     */
    public void setUpdatedDate(Date value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * @param customersId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer customersId) {
        return new Key(new Object[] { customersId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.sgs.model.entity.SgsCustomers");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        try {
            SGSAppModuleImpl am = new SGSAppModuleImpl();
            setCustomersId(am.getDBSequence("SGS_CUSTOMERS_SEQ"));
        } catch (Exception e) {
            LOG.severe(e);
        }
    }
}

