package com.sgs.model.service;


import com.sgs.model.view.SgsCustomersVOImpl;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.sql.SQLException;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 12 19:34:13 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SGSAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SGSAppModuleImpl() {
    }

    private static final ADFLogger LOG = ADFLogger.createADFLogger(SGSAppModuleImpl.class);

    /**
     * Container's getter for SgsAccPayInvoicesVO1.
     * @return SgsAccPayInvoicesVO1
     */
    public ViewObjectImpl getSgsAccPayInvoicesVO1() {
        return (ViewObjectImpl) findViewObject("SgsAccPayInvoicesVO1");
    }

    /**
     * Container's getter for SgsAccRecInvoicesVO1.
     * @return SgsAccRecInvoicesVO1
     */
    public ViewObjectImpl getSgsAccRecInvoicesVO1() {
        return (ViewObjectImpl) findViewObject("SgsAccRecInvoicesVO1");
    }

    /**
     * Container's getter for SgsBillTypeVO1.
     * @return SgsBillTypeVO1
     */
    public ViewObjectImpl getSgsBillTypeVO1() {
        return (ViewObjectImpl) findViewObject("SgsBillTypeVO1");
    }

    /**
     * Container's getter for SgsBusinessUnitsVO1.
     * @return SgsBusinessUnitsVO1
     */
    public ViewObjectImpl getSgsBusinessUnitsVO1() {
        return (ViewObjectImpl) findViewObject("SgsBusinessUnitsVO1");
    }

    /**
     * Container's getter for SgsContractHeaderVO1.
     * @return SgsContractHeaderVO1
     */
    public ViewObjectImpl getSgsContractHeaderVO1() {
        return (ViewObjectImpl) findViewObject("SgsContractHeaderVO1");
    }

    /**
     * Container's getter for SgsCustomersVO1.
     * @return SgsCustomersVO1
     */
    public SgsCustomersVOImpl getSgsCustomersVO1() {
        return (SgsCustomersVOImpl) findViewObject("SgsCustomersVO1");
    }

    /**
     * Container's getter for SgsProjectsVO1.
     * @return SgsProjectsVO1
     */
    public ViewObjectImpl getSgsProjectsVO1() {
        return (ViewObjectImpl) findViewObject("SgsProjectsVO1");
    }

    /**
     * Container's getter for SgsServicesVO1.
     * @return SgsServicesVO1
     */
    public ViewObjectImpl getSgsServicesVO1() {
        return (ViewObjectImpl) findViewObject("SgsServicesVO1");
    }

    /**
     * Container's getter for SgsSuppliersVO1.
     * @return SgsSuppliersVO1
     */
    public ViewObjectImpl getSgsSuppliersVO1() {
        return (ViewObjectImpl) findViewObject("SgsSuppliersVO1");
    }

    /**
     * Container's getter for SgsBUCustomersVO.
     * @return SgsBUCustomersVO
     */
    public SgsCustomersVOImpl getSgsBUCustomersVO() {
        return (SgsCustomersVOImpl) findViewObject("SgsBUCustomersVO");
    }

    /**
     * Container's getter for SgsBUAccPayPaymentsVO.
     * @return SgsBUAccPayPaymentsVO
     */
    public ViewObjectImpl getSgsBUAccPayPaymentsVO() {
        return (ViewObjectImpl) findViewObject("SgsBUAccPayPaymentsVO");
    }

    /**
     * Container's getter for SgsBUAccRecInvoicesVO.
     * @return SgsBUAccRecInvoicesVO
     */
    public ViewObjectImpl getSgsBUAccRecInvoicesVO() {
        return (ViewObjectImpl) findViewObject("SgsBUAccRecInvoicesVO");
    }

    /**
     * Container's getter for SgsBUAccRecPaymentsVO.
     * @return SgsBUAccRecPaymentsVO
     */
    public ViewObjectImpl getSgsBUAccRecPaymentsVO() {
        return (ViewObjectImpl) findViewObject("SgsBUAccRecPaymentsVO");
    }

    /**
     * Container's getter for SgsBUContractHeaderVO.
     * @return SgsBUContractHeaderVO
     */
    public ViewObjectImpl getSgsBUContractHeaderVO() {
        return (ViewObjectImpl) findViewObject("SgsBUContractHeaderVO");
    }

    /**
     * Container's getter for SgsBUContractLinesVO.
     * @return SgsBUContractLinesVO
     */
    public ViewObjectImpl getSgsBUContractLinesVO() {
        return (ViewObjectImpl) findViewObject("SgsBUContractLinesVO");
    }

    /**
     * Container's getter for SgsBUProjectsVO.
     * @return SgsBUProjectsVO
     */
    public ViewObjectImpl getSgsBUProjectsVO() {
        return (ViewObjectImpl) findViewObject("SgsBUProjectsVO");
    }

    /**
     * Container's getter for SgsBUServicesVO.
     * @return SgsBUServicesVO
     */
    public ViewObjectImpl getSgsBUServicesVO() {
        return (ViewObjectImpl) findViewObject("SgsBUServicesVO");
    }

    /**
     * Container's getter for SgsBUSuppliersVO.
     * @return SgsBUSuppliersVO
     */
    public ViewObjectImpl getSgsBUSuppliersVO() {
        return (ViewObjectImpl) findViewObject("SgsBUSuppliersVO");
    }

    /**
     * Container's getter for SgsCustomersAccRecInvoicesVO.
     * @return SgsCustomersAccRecInvoicesVO
     */
    public ViewObjectImpl getSgsCustomersAccRecInvoicesVO() {
        return (ViewObjectImpl) findViewObject("SgsCustomersAccRecInvoicesVO");
    }

    /**
     * Container's getter for SgsCustomersContractHeaderVO.
     * @return SgsCustomersContractHeaderVO
     */
    public ViewObjectImpl getSgsCustomersContractHeaderVO() {
        return (ViewObjectImpl) findViewObject("SgsCustomersContractHeaderVO");
    }

    /**
     * Container's getter for SgsCustomersProjectsVO.
     * @return SgsCustomersProjectsVO
     */
    public ViewObjectImpl getSgsCustomersProjectsVO() {
        return (ViewObjectImpl) findViewObject("SgsCustomersProjectsVO");
    }

    /**
     * Container's getter for SgsSuppliersAccPayInvoicesVO.
     * @return SgsSuppliersAccPayInvoicesVO
     */
    public ViewObjectImpl getSgsSuppliersAccPayInvoicesVO() {
        return (ViewObjectImpl) findViewObject("SgsSuppliersAccPayInvoicesVO");
    }

    /**
     * Container's getter for SgsServicesAccPayInvoicesVO.
     * @return SgsServicesAccPayInvoicesVO
     */
    public ViewObjectImpl getSgsServicesAccPayInvoicesVO() {
        return (ViewObjectImpl) findViewObject("SgsServicesAccPayInvoicesVO");
    }

    /**
     * Container's getter for SgsServicesAccRecInvoicesVO.
     * @return SgsServicesAccRecInvoicesVO
     */
    public ViewObjectImpl getSgsServicesAccRecInvoicesVO() {
        return (ViewObjectImpl) findViewObject("SgsServicesAccRecInvoicesVO");
    }

    /**
     * Container's getter for SgsServicesContractLinesVO.
     * @return SgsServicesContractLinesVO
     */
    public ViewObjectImpl getSgsServicesContractLinesVO() {
        return (ViewObjectImpl) findViewObject("SgsServicesContractLinesVO");
    }

    /**
     * Container's getter for SgsServicesSuppliersVO.
     * @return SgsServicesSuppliersVO
     */
    public ViewObjectImpl getSgsServicesSuppliersVO() {
        return (ViewObjectImpl) findViewObject("SgsServicesSuppliersVO");
    }

    /**
     * Container's getter for SgsContractHeaderToLinesVO.
     * @return SgsContractHeaderToLinesVO
     */
    public ViewObjectImpl getSgsContractHeaderToLinesVO() {
        return (ViewObjectImpl) findViewObject("SgsContractHeaderToLinesVO");
    }

    /**
     * Container's getter for SgsARInvoicetoARPaymentsVO.
     * @return SgsARInvoicetoARPaymentsVO
     */
    public ViewObjectImpl getSgsARInvoicetoARPaymentsVO() {
        return (ViewObjectImpl) findViewObject("SgsARInvoicetoARPaymentsVO");
    }

    /**
     * Container's getter for SgsAPInvoiceToAPPaymentVO.
     * @return SgsAPInvoiceToAPPaymentVO
     */
    public ViewObjectImpl getSgsAPInvoiceToAPPaymentVO() {
        return (ViewObjectImpl) findViewObject("SgsAPInvoiceToAPPaymentVO");
    }

    /**
     * Container's getter for SgsBillTypeAccRecInvoicesVO.
     * @return SgsBillTypeAccRecInvoicesVO
     */
    public ViewObjectImpl getSgsBillTypeAccRecInvoicesVO() {
        return (ViewObjectImpl) findViewObject("SgsBillTypeAccRecInvoicesVO");
    }

    /**
     * Container's getter for SgsBillTypeContractHeaderVO.
     * @return SgsBillTypeContractHeaderVO
     */
    public ViewObjectImpl getSgsBillTypeContractHeaderVO() {
        return (ViewObjectImpl) findViewObject("SgsBillTypeContractHeaderVO");
    }

    /**
     * Container's getter for SgsBillTypeProjectsVO.
     * @return SgsBillTypeProjectsVO
     */
    public ViewObjectImpl getSgsBillTypeProjectsVO() {
        return (ViewObjectImpl) findViewObject("SgsBillTypeProjectsVO");
    }

    /**
     * Container's getter for SgsProjectsAccRecInvoicesVO.
     * @return SgsProjectsAccRecInvoicesVO
     */
    public ViewObjectImpl getSgsProjectsAccRecInvoicesVO() {
        return (ViewObjectImpl) findViewObject("SgsProjectsAccRecInvoicesVO");
    }

    /**
     * Container's getter for SgsBUCustomersVL1.
     * @return SgsBUCustomersVL1
     */
    public ViewLinkImpl getSgsBUCustomersVL1() {
        return (ViewLinkImpl) findViewLink("SgsBUCustomersVL1");
    }

    /**
     * Container's getter for SgsBUAccPayPaymentVL2.
     * @return SgsBUAccPayPaymentVL2
     */
    public ViewLinkImpl getSgsBUAccPayPaymentVL2() {
        return (ViewLinkImpl) findViewLink("SgsBUAccPayPaymentVL2");
    }

    /**
     * Container's getter for SgsBUAccRecInvoicesVL1.
     * @return SgsBUAccRecInvoicesVL1
     */
    public ViewLinkImpl getSgsBUAccRecInvoicesVL1() {
        return (ViewLinkImpl) findViewLink("SgsBUAccRecInvoicesVL1");
    }

    /**
     * Container's getter for SgsBUAccRecPaymentVL1.
     * @return SgsBUAccRecPaymentVL1
     */
    public ViewLinkImpl getSgsBUAccRecPaymentVL1() {
        return (ViewLinkImpl) findViewLink("SgsBUAccRecPaymentVL1");
    }

    /**
     * Container's getter for SgsBUContractHeaderVL1.
     * @return SgsBUContractHeaderVL1
     */
    public ViewLinkImpl getSgsBUContractHeaderVL1() {
        return (ViewLinkImpl) findViewLink("SgsBUContractHeaderVL1");
    }

    /**
     * Container's getter for SgsBUContractLinesVL1.
     * @return SgsBUContractLinesVL1
     */
    public ViewLinkImpl getSgsBUContractLinesVL1() {
        return (ViewLinkImpl) findViewLink("SgsBUContractLinesVL1");
    }

    /**
     * Container's getter for SgsBUProjectsVL1.
     * @return SgsBUProjectsVL1
     */
    public ViewLinkImpl getSgsBUProjectsVL1() {
        return (ViewLinkImpl) findViewLink("SgsBUProjectsVL1");
    }

    /**
     * Container's getter for SgsBUServicesVL1.
     * @return SgsBUServicesVL1
     */
    public ViewLinkImpl getSgsBUServicesVL1() {
        return (ViewLinkImpl) findViewLink("SgsBUServicesVL1");
    }

    /**
     * Container's getter for SgsBUSuppliersVL1.
     * @return SgsBUSuppliersVL1
     */
    public ViewLinkImpl getSgsBUSuppliersVL1() {
        return (ViewLinkImpl) findViewLink("SgsBUSuppliersVL1");
    }

    /**
     * Container's getter for SgsCustomersAccRecInvoicesVL2.
     * @return SgsCustomersAccRecInvoicesVL2
     */
    public ViewLinkImpl getSgsCustomersAccRecInvoicesVL2() {
        return (ViewLinkImpl) findViewLink("SgsCustomersAccRecInvoicesVL2");
    }

    /**
     * Container's getter for SgsCustomersContractHeaderVL1.
     * @return SgsCustomersContractHeaderVL1
     */
    public ViewLinkImpl getSgsCustomersContractHeaderVL1() {
        return (ViewLinkImpl) findViewLink("SgsCustomersContractHeaderVL1");
    }

    /**
     * Container's getter for SgsCustomersProjectsVL1.
     * @return SgsCustomersProjectsVL1
     */
    public ViewLinkImpl getSgsCustomersProjectsVL1() {
        return (ViewLinkImpl) findViewLink("SgsCustomersProjectsVL1");
    }

    /**
     * Container's getter for SgsSuppliersAccPayInvoiceVL1.
     * @return SgsSuppliersAccPayInvoiceVL1
     */
    public ViewLinkImpl getSgsSuppliersAccPayInvoiceVL1() {
        return (ViewLinkImpl) findViewLink("SgsSuppliersAccPayInvoiceVL1");
    }

    /**
     * Container's getter for SgsServicesAccPayInvoices1.
     * @return SgsServicesAccPayInvoices1
     */
    public ViewLinkImpl getSgsServicesAccPayInvoices1() {
        return (ViewLinkImpl) findViewLink("SgsServicesAccPayInvoices1");
    }

    /**
     * Container's getter for SgsServicesAccRecInvoicesVL1.
     * @return SgsServicesAccRecInvoicesVL1
     */
    public ViewLinkImpl getSgsServicesAccRecInvoicesVL1() {
        return (ViewLinkImpl) findViewLink("SgsServicesAccRecInvoicesVL1");
    }

    /**
     * Container's getter for SgsServicesContractLinesVL1.
     * @return SgsServicesContractLinesVL1
     */
    public ViewLinkImpl getSgsServicesContractLinesVL1() {
        return (ViewLinkImpl) findViewLink("SgsServicesContractLinesVL1");
    }

    /**
     * Container's getter for SgsServicesSuppliersVL1.
     * @return SgsServicesSuppliersVL1
     */
    public ViewLinkImpl getSgsServicesSuppliersVL1() {
        return (ViewLinkImpl) findViewLink("SgsServicesSuppliersVL1");
    }

    /**
     * Container's getter for SgsContractHeaderContractLinsVL1.
     * @return SgsContractHeaderContractLinsVL1
     */
    public ViewLinkImpl getSgsContractHeaderContractLinsVL1() {
        return (ViewLinkImpl) findViewLink("SgsContractHeaderContractLinsVL1");
    }

    /**
     * Container's getter for SgsARInvoicesToARPaymentVL1.
     * @return SgsARInvoicesToARPaymentVL1
     */
    public ViewLinkImpl getSgsARInvoicesToARPaymentVL1() {
        return (ViewLinkImpl) findViewLink("SgsARInvoicesToARPaymentVL1");
    }

    /**
     * Container's getter for SgsAPInvoiceToAPPaymentVL1.
     * @return SgsAPInvoiceToAPPaymentVL1
     */
    public ViewLinkImpl getSgsAPInvoiceToAPPaymentVL1() {
        return (ViewLinkImpl) findViewLink("SgsAPInvoiceToAPPaymentVL1");
    }

    /**
     * Container's getter for SgsBillTypeARInvoiceVL1.
     * @return SgsBillTypeARInvoiceVL1
     */
    public ViewLinkImpl getSgsBillTypeARInvoiceVL1() {
        return (ViewLinkImpl) findViewLink("SgsBillTypeARInvoiceVL1");
    }

    /**
     * Container's getter for SgsBillTypeContractHeaderVL1.
     * @return SgsBillTypeContractHeaderVL1
     */
    public ViewLinkImpl getSgsBillTypeContractHeaderVL1() {
        return (ViewLinkImpl) findViewLink("SgsBillTypeContractHeaderVL1");
    }

    /**
     * Container's getter for SgsBillTypeProjectsVL1.
     * @return SgsBillTypeProjectsVL1
     */
    public ViewLinkImpl getSgsBillTypeProjectsVL1() {
        return (ViewLinkImpl) findViewLink("SgsBillTypeProjectsVL1");
    }

    /**
     * Container's getter for SgsProjectsARInvoicesVL1.
     * @return SgsProjectsARInvoicesVL1
     */
    public ViewLinkImpl getSgsProjectsARInvoicesVL1() {
        return (ViewLinkImpl) findViewLink("SgsProjectsARInvoicesVL1");
    }
    
    /**
     * @param seqName
     * @return sequence next value
     */
    public int getDBSequence(String seqName) {
        Connection conn = null;
        PreparedStatement pst = null;
        try {
            String connectionUrl =
                "jdbc:sqlserver://localhost;instanceName=MSSQLSERVER;databasename=SGS;integratedSecurity=true;";
            conn = DriverManager.getConnection(connectionUrl);
            String sqlIdentifier = "select next value for " + seqName;
            pst = conn.prepareStatement(sqlIdentifier);

            ResultSet rs = pst.executeQuery();
            if (rs.next())
                rs.getInt(1);
            
            return rs.getInt(1);
        } catch (SQLException sqle) {
            LOG.severe(sqle);
        } finally {
            try {
                conn.close();
                pst.close();
            } catch (SQLException e) {
                LOG.severe(e);
            }
        }
        return 0;
    }

    /**
     * Container's getter for SgsApInvoiceLinesVO1.
     * @return SgsApInvoiceLinesVO1
     */
    public ViewObjectImpl getSgsApInvoiceLinesVO1() {
        return (ViewObjectImpl) findViewObject("SgsApInvoiceLinesVO1");
    }

    /**
     * Container's getter for SgsApInvoiceApLinesVL1.
     * @return SgsApInvoiceApLinesVL1
     */
    public ViewLinkImpl getSgsApInvoiceApLinesVL1() {
        return (ViewLinkImpl) findViewLink("SgsApInvoiceApLinesVL1");
    }

    /**
     * Container's getter for SgsArInvoiceLinesVO1.
     * @return SgsArInvoiceLinesVO1
     */
    public ViewObjectImpl getSgsArInvoiceLinesVO1() {
        return (ViewObjectImpl) findViewObject("SgsArInvoiceLinesVO1");
    }

    /**
     * Container's getter for SgsArInvoiceArLinesVL1.
     * @return SgsArInvoiceArLinesVL1
     */
    public ViewLinkImpl getSgsArInvoiceArLinesVL1() {
        return (ViewLinkImpl) findViewLink("SgsArInvoiceArLinesVL1");
    }

    /**
     * Container's getter for SgsUsersByBuVO1.
     * @return SgsUsersByBuVO1
     */
    public ViewObjectImpl getSgsUsersByBuVO() {
        return (ViewObjectImpl) findViewObject("SgsUsersByBuVO");
    }


    /**
     * Container's getter for SgsApPaymentsVO1.
     * @return SgsApPaymentsVO1
     */
    public ViewObjectImpl getSgsApPaymentsVO1() {
        return (ViewObjectImpl) findViewObject("SgsApPaymentsVO1");
    }

    /**
     * Container's getter for SgsApInvPaymentsVO1.
     * @return SgsApInvPaymentsVO1
     */
    public ViewObjectImpl getSgsApInvPaymentsVO1() {
        return (ViewObjectImpl) findViewObject("SgsApInvPaymentsVO1");
    }

    /**
     * Container's getter for SgsPaymentHdrDtlVL1.
     * @return SgsPaymentHdrDtlVL1
     */
    public ViewLinkImpl getSgsPaymentHdrDtlVL1() {
        return (ViewLinkImpl) findViewLink("SgsPaymentHdrDtlVL1");
    }

    /**
     * Container's getter for SgsApInvPaymentsVO2.
     * @return SgsApInvPaymentsVO2
     */
    public ViewObjectImpl getSgsApInvPaymentsVO2() {
        return (ViewObjectImpl) findViewObject("SgsApInvPaymentsVO2");
    }

    /**
     * Container's getter for SgsApInvPaymentsVL1.
     * @return SgsApInvPaymentsVL1
     */
    public ViewLinkImpl getSgsApInvPaymentsVL1() {
        return (ViewLinkImpl) findViewLink("SgsApInvPaymentsVL1");
    }

    /**
     * Container's getter for SgsArReceiptDtlVO1.
     * @return SgsArReceiptDtlVO1
     */
    public ViewObjectImpl getSgsArReceiptDtlVO1() {
        return (ViewObjectImpl) findViewObject("SgsArReceiptDtlVO1");
    }

    /**
     * Container's getter for SgsArInvReceiptVL1.
     * @return SgsArInvReceiptVL1
     */
    public ViewLinkImpl getSgsArInvReceiptVL1() {
        return (ViewLinkImpl) findViewLink("SgsArInvReceiptVL1");
    }

    /**
     * Container's getter for SgsArReceiptVO1.
     * @return SgsArReceiptVO1
     */
    public ViewObjectImpl getSgsArReceiptVO1() {
        return (ViewObjectImpl) findViewObject("SgsArReceiptVO1");
    }

    /**
     * Container's getter for SgsArReceiptDtlVO2.
     * @return SgsArReceiptDtlVO2
     */
    public ViewObjectImpl getSgsArReceiptDtlVO2() {
        return (ViewObjectImpl) findViewObject("SgsArReceiptDtlVO2");
    }

    /**
     * Container's getter for SgsArReceiptHdrDtlVL1.
     * @return SgsArReceiptHdrDtlVL1
     */
    public ViewLinkImpl getSgsArReceiptHdrDtlVL1() {
        return (ViewLinkImpl) findViewLink("SgsArReceiptHdrDtlVL1");
    }

    /**
     * Container's getter for SgsListVO1.
     * @return SgsListVO1
     */
    public ViewObjectImpl getSgsListVO1() {
        return (ViewObjectImpl) findViewObject("SgsListVO1");
    }

    /**
     * Container's getter for SgsCostIdentificationRuleView1.
     * @return SgsCostIdentificationRuleView1
     */
    public ViewObjectImpl getSgsCostIdentificationRuleView1() {
        return (ViewObjectImpl) findViewObject("SgsCostIdentificationRuleView1");
    }

    /**
     * Container's getter for SgsTransBCostAllocationView1.
     * @return SgsTransBCostAllocationView1
     */
    public ViewObjectImpl getSgsTransBCostAllocationView1() {
        return (ViewObjectImpl) findViewObject("SgsTransBCostAllocationView1");
    }

    /**
     * Container's getter for SgsBusinessUnitMasterVO1.
     * @return SgsBusinessUnitMasterVO1
     */
    public ViewObjectImpl getSgsBusinessUnitMasterVO1() {
        return (ViewObjectImpl) findViewObject("SgsBusinessUnitMasterVO1");
    }

    /**
     * Container's getter for SgsAllocationRuleSetupVO1.
     * @return SgsAllocationRuleSetupVO1
     */
    public ViewObjectImpl getSgsAllocationRuleSetupVO1() {
        return (ViewObjectImpl) findViewObject("SgsAllocationRuleSetupVO1");
    }

    /**
     * Container's getter for SgsTpaMasterVO1.
     * @return SgsTpaMasterVO1
     */
    public ViewObjectImpl getSgsTpaMasterVO1() {
        return (ViewObjectImpl) findViewObject("SgsTpaMasterVO1");
    }

    /**
     * Container's getter for SgsStandarardRateVO1.
     * @return SgsStandarardRateVO1
     */
    public ViewObjectImpl getSgsStandarardRateVO1() {
        return (ViewObjectImpl) findViewObject("SgsStandarardRateVO1");
    }

    /**
     * Container's getter for SgsRevAllocatedDataVO1.
     * @return SgsRevAllocatedDataVO1
     */
    public ViewObjectImpl getSgsRevAllocatedDataVO() {
        return (ViewObjectImpl) findViewObject("SgsRevAllocatedDataVO");
    }
}

